package bitcamp.java110.cms.dao.impl;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.List;

import bitcamp.java110.cms.annotation.Component;
import bitcamp.java110.cms.dao.DaoException;
import bitcamp.java110.cms.dao.ManagerDao;
import bitcamp.java110.cms.domain.Manager;

// 자동생성하게
@Component
public class ManagerMysqlDao implements ManagerDao {

    public int insert(Manager manager) {
        
        Connection con = null;
        Statement stmt = null;
        
        try {
            // 매니저 정보를 입력할 때 p1_memb 테이블과 p1_mgt 테이블에 
            // 매니저 정보를 분산 입력 해야 한다.
            // 두 테이블에 모두 입력 성공할 때 입력을 완료하도록 
            // 두 insert를 한 작업(transaction)으로 묶는다.
            // => SQL을 서버에 보낸 후 클라이언트가 최종 완료 신호를
            //    보내기 전까지는 처리를 보류하도록 설정한다.
            Class.forName("org.mariadb.jdbc.Driver");
            con = DriverManager.getConnection(
                    "jdbc:mariadb://localhost:3306/studydb"
                    , "study", "1111");
            con.setAutoCommit(false);

            stmt = con.createStatement();
            
            String sql = "insert into p1_memb(name, email, pwd, tel, cdt)"
                    + "values('" + manager.getName()
                    + "','" + manager.getEmail()
                    + "',password('" + manager.getPassword()
                    + "'),'" + manager.getTel()
                    + "',now())";    //now()와 password()는 mariadb함수

            System.out.println(sql);
            
            // p1_memb 테이블에 회원 기본 정보를 입력 한 후
            // 자동으로 생성된 회원 번호를 리턴 받는다.
            stmt.executeUpdate(sql, Statement.RETURN_GENERATED_KEYS);   //자동으로 숫자올리기?
            
            //insert를 실행한 후 리턴받은 자동증가 PK값을 꺼내기
            ResultSet autogeneratedKeys = stmt.getGeneratedKeys(); 
            autogeneratedKeys.next();
            int memberNo = autogeneratedKeys.getInt(1); //resultset은 arraylist등과 다르게 1부터시작.
            autogeneratedKeys.close(); //번호를 가져왔으니 닫아도 됨
            
            // 회원 번호로 매니저 테이블에 직위 정보를 입력한다.
            String sql2 = "insert into p1_mgr(mrno, posi)"
                    + " values(" +memberNo
                    + ",'" + manager.getPosition()
                    + "')";
            stmt.executeUpdate(sql2);
            
            // 두 insert가 모두 성공했을 때만 서버에 완료 신호를 보낸다.
            con.commit();
            return 1;
        }catch (Exception e) {
            throw new DaoException(e);
        }finally {
            try{ stmt.close(); } catch(Exception e) {}
            try{ con.close(); } catch(Exception e) {}
        }
        //실패했을 경우에는 여기까지 닿지 않기 때문에 return 0 할 필요 X
    }

    public List<Manager> findAll(){ //밑에서 catch가 던지는것이 runtime exception이기 때문에 메서드 옆에 붙이지 않아도 됨.

        ArrayList<Manager> list = new ArrayList<>();
        Connection con = null;
        Statement stmt = null;
        ResultSet rs = null;    //결과를 가져오기 위해서.
        
        try {
            // => java.sql.Driver 구현체를 로딩한다.
            // => 해당 클래스의 객체를 만들어 DriverManager에 등록한다.
            Class.forName("org.mariadb.jdbc.Driver");

            //DriverManager.registerDriver(new org.mariadb.jdbc.Driver());
            // => DriverManager에게 java.sql.Connection 객체를 요구한다.
            // => DriverManager는 등록된 Driver들 중에서 요구 사항에 맞는
            //    드라이버를 찾아 connect()를 호출한다.
            //    그리고 connect() 메서드의 리턴값을 그대로 리턴해준다.

            // 위의 한줄과 같은 기능. 객체 만들어서 등록해야함! 근데 Driver 클래스에 가보면 static으로 로딩되면서
            // 자동으로 객체를 만들어주기 때문에 객체를 우리가 만들어 줄 필요가 없음. => 따라서 위의 한줄로 대체 가능!

            con = DriverManager.getConnection(
                    "jdbc:mariadb://localhost:3306/studydb"
                    , "study", "1111");

            // => 질의문을 작성할 객체를 준비한다.
            stmt = con.createStatement();

            // => select 질의를 한다. 
            /*
             * select 
             *      m.name,
             *      m.email,
             *      mr.posi
             * from p1_mgr mr inner join p1_memb m  // 여기서 inner는 넣어도, 안넣어도 inner join!
             * on mr.mrno = m.mno;

             * select 
             *      m.name,
             *      m.email,
             *      mr.posi
             * from p1_mgr mr right outer join p1_memb m  //오른쪽을 기준으로 오른쪽에 해당하는것 모두 출력
             * on mr.mrno = m.mno;
             *
             *
             */
            //resultset은 서버에 가서 
            rs = stmt.executeQuery(
                    "  select " + 
                            "  m.mno," +
                            "  m.name," + 
                            "  m.email," + 
                            "  mr.posi" + 
                            "  from p1_mgr mr inner join p1_memb m" + 
                            "  on mr.mrno = m.mno");    //sql안에 ;넣지 않음.
            // 서버에 생성된 질의 결과를 한개씩 가져온다.
            while(rs.next()) {
                Manager mgr = new Manager();    //바깥으로 뽑으면 arraylist에 기존데이터가 날아가고 모든 것이 같은 주소를 가리키게 됨.
                mgr.setNo(rs.getInt("mno"));
                mgr.setEmail(rs.getString("email"));
                mgr.setName(rs.getString("name"));
                mgr.setPosition(rs.getString("posi"));

                list.add(mgr);
            }
        }catch (Exception e) {
            throw new DaoException(e);
        }finally {
            try{ rs.close(); } catch(Exception e) {}
            try{ stmt.close(); } catch(Exception e) {}
            try{ con.close(); } catch(Exception e) {}
        }
        return list;
        //name과 mail,posi를 select했기 때문에 이외의 자리에는 null이 반환된다.
    }

    public Manager findByEmail(String email) {
        
        Connection con = null;
        Statement stmt = null;
        ResultSet rs = null;    //결과를 가져오기 위해서.
        
        try {
            Class.forName("org.mariadb.jdbc.Driver");
            con = DriverManager.getConnection(
                    "jdbc:mariadb://localhost:3306/studydb"
                    , "study", "1111");

            stmt = con.createStatement();
            rs = stmt.executeQuery(
                    "  select " + 
                            "  m.mno," +
                            "  m.name," + 
                            "  m.email," +
                            "  m.tel," + 
                            "  mr.posi" + 
                            "  from p1_mgr mr inner join p1_memb m" + 
                            "  on mr.mrno = m.mno" +
                            "  where m.email = '" + email +"'");    //sql안에 ;넣지 않음.

            if(rs.next()) {
                Manager mgr = new Manager();    //바깥으로 뽑으면 arraylist에 기존데이터가 날아가고 모든 것이 같은 주소를 가리키게 됨.
                mgr.setNo(rs.getInt("mno"));
                mgr.setEmail(rs.getString("email"));
                mgr.setName(rs.getString("name"));
                mgr.setTel(rs.getString("tel"));
                mgr.setPosition(rs.getString("posi"));

                return mgr;
            }
            
            return null;
            
        }catch (Exception e) {
            throw new DaoException(e);
        }finally {
            try{ rs.close(); } catch(Exception e) {}
            try{ stmt.close(); } catch(Exception e) {}
            try{ con.close(); } catch(Exception e) {}
        }

    }
   
    public Manager findByNo(int no) {
        
        Connection con = null;
        Statement stmt = null;
        ResultSet rs = null;   
        
        try {
            Class.forName("org.mariadb.jdbc.Driver");
            con = DriverManager.getConnection(
                    "jdbc:mariadb://localhost:3306/studydb"
                    , "study", "1111");

            stmt = con.createStatement();
            rs = stmt.executeQuery(
                    "  select " + 
                            "  m.mno," +
                            "  m.name," + 
                            "  m.email," +
                            "  m.tel," + 
                            "  mr.posi" + 
                            "  from p1_mgr mr inner join p1_memb m" + 
                            "  on mr.mrno = m.mno" +
                            "  where m.mno = " + no);    //sql안에 ;넣지 않음.

            if(rs.next()) {
                Manager mgr = new Manager();    //바깥으로 뽑으면 arraylist에 기존데이터가 날아가고 모든 것이 같은 주소를 가리키게 됨.
                mgr.setNo(rs.getInt("mno"));
                mgr.setEmail(rs.getString("email"));
                mgr.setName(rs.getString("name"));
                mgr.setTel(rs.getString("tel"));
                mgr.setPosition(rs.getString("posi"));

                return mgr;
            }
            
            return null;
            
        }catch (Exception e) {
            throw new DaoException(e);
        }finally {
            try{ rs.close(); } catch(Exception e) {}
            try{ stmt.close(); } catch(Exception e) {}
            try{ con.close(); } catch(Exception e) {}
        }

    }
    
    
    public int delete(int no) {
        
        Connection con = null;
        Statement stmt = null;
        
        try {
            Class.forName("org.mariadb.jdbc.Driver");
            con = DriverManager.getConnection(
                    "jdbc:mariadb://localhost:3306/studydb"
                    , "study", "1111");
            
            con.setAutoCommit(false);
            stmt = con.createStatement();
            

            String sql = "delete from p1_mgr where mrno = " + no; //자식먼저삭제
            int count = stmt.executeUpdate(sql);
            
            if(count ==0)
                return 0;
            
            String sql2 = "delete from p1_memb where mno = " + no; //부모삭제
            stmt.executeUpdate(sql2);
            con.commit();
            
            return 1;
            
        }catch (Exception e) {
            throw new DaoException(e);
        }finally {
            try{ stmt.close(); } catch(Exception e) {}
            try{ con.close(); } catch(Exception e) {}
        }

    }
    
    
    
    
    
    
}
